// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSIFyuqKWF06rjGYwgERXxaaz_fxI2_E',
    appId: '1:901508578456:web:5ddb9decac71cdb973e4ed',
    messagingSenderId: '901508578456',
    projectId: 'kaigofika-poc01',
    authDomain: 'kaigofika-poc01.firebaseapp.com',
    storageBucket: 'kaigofika-poc01.appspot.com',
    measurementId: 'G-XHNS4ZXNXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCTRpcEeSZ1BZJPvqT3EjKhAVZNzTeYk',
    appId: '1:901508578456:android:4481bba8cf5198c873e4ed',
    messagingSenderId: '901508578456',
    projectId: 'kaigofika-poc01',
    storageBucket: 'kaigofika-poc01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrV3ssQzszpBLiA3Y36B2wOfy_Ijty50',
    appId: '1:901508578456:ios:c512224b16dbd69173e4ed',
    messagingSenderId: '901508578456',
    projectId: 'kaigofika-poc01',
    storageBucket: 'kaigofika-poc01.appspot.com',
    iosClientId: '901508578456-0qg3v5nlj61k207cs75b65kv5amudj3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrV3ssQzszpBLiA3Y36B2wOfy_Ijty50',
    appId: '1:901508578456:ios:c5d5fc80d5a4b49973e4ed',
    messagingSenderId: '901508578456',
    projectId: 'kaigofika-poc01',
    storageBucket: 'kaigofika-poc01.appspot.com',
    iosClientId: '901508578456-i7lh8m7kgp202ia70v5pv2hcn2ipfqsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
